config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  # Static
  get '/learn' => 'pages#learn'
  get '/search' => 'pages#search'
  get '/apply' => 'pages#apply'

  # Dynamic
  get '/lookup' => 'patterns#lookup'
  get '/radius' => 'patterns#radius'
  get '/district' => 'patterns#district'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/geocodable.rb
module Geocodable
  extend ActiveSupport::Concern

  #
  # Geocoable Concern
  #
  # Adds geocoding to the model so that it can be managed appropriately.
  #

  ADDRESS_FIELDS = %w[addres1 address2 address city state zip postal county country]

  included do
    before_save :geocode, if: ->(s) { !s.geocoded? || (ADDRESS_FIELDS & s.changes.keys).length > 0 }

    geocoded_by :address do |obj, results|
      if geo = results.first
        obj.coords = "POINT(#{geo.longitude.to_f} #{geo.latitude.to_f})"
      end
    end
  end

  def geocode!
    unless geocoded?
      puts "Geocoding: #{name}"
      geocode
      save if changed?
    end
  end

  def latitude
    coords&.lat
  end
  alias_method :lat, :latitude

  def latitude=(value)
    coords = "POINT(#{longitude} #{value.to_f})"
  end
  alias_method :lat=, :latitude=

  def longitude
    coords&.lon
  end
  alias_method :lon, :longitude

  def longitude=(value)
    coords = "POINT(#{value.to_f} #{latitude})"
  end
  alias_method :lon=, :longitude=
end

app/models/district.rb
class District < ApplicationRecord
  include Geocodable

  has_many :feeder_pattern
  has_many :schools

  scope :no_geom, -> { select(column_names.map(&:to_sym).reject { |s| s == :geom }) }
  scope :containing, ->(lat, lon) { where(Arel.sql("ST_intersects(districts.geom, ST_POINT(#{lon.to_f}, #{lat.to_f}))")) }

  def self.raw_geom(id)
    sql = <<~SQL
      SELECT ST_AsGeoJSON(geom::geometry) geom_json
      FROM districts
      WHERE id = #{id.to_i}
    SQL
    ActiveRecord::Base.connection.execute(sql).first['geom_json']
  end
end

app/models/feeder_pattern.rb
class FeederPattern < ApplicationRecord
  belongs_to :district
  belongs_to :school, optional: true

  scope :grade, ->(grade) { where(grade_level: grade.downcase) }
  scope :containing, ->(lat, lon) { where(Arel.sql("ST_intersects(feeder_patterns.geom, ST_POINT(#{lon.to_f}, #{lat.to_f}))")) }
  scope :no_geom, -> { select(column_names.map(&:to_sym).reject { |s| s == :geom }) }
end

app/models/school.rb
class School < ApplicationRecord
  include Geocodable

  belongs_to :district, optional: true
  has_many :feeder_patterns

  GRADE_KEYS = %w[earlychildhood prekindergarten kindergarten one two three four five six seven eight nine ten eleven twelve].freeze
  GRADE_NAMES = [
    'Early Childhood', 'Pre-Kindergarten', 'Kindergarten',
    'First Grade', 'Second Grade', 'Third Grade', 'Fourth Grade',
    'Fifth Grade', 'Sixth Grade', 'Seventh Grade', 'Eighth Grade',
    'Ninth Grade (Freshman)', 'Tenth Grade (Sophomore)',
    'Eleventh Grade (Junior)', 'Twelfth Grade (Senior)'
  ].freeze
  GRADE_LEVELS = GRADE_KEYS.zip(GRADE_NAMES).to_h.freeze

  scope :within_radius, -> (lat, lon, r) { where(Arel.sql("ST_dwithin(schools.coords, ST_POINT(#{lon.to_f}, #{lat.to_f}), #{r.to_f})")) }
  scope :no_geom, -> { select(column_names.map(&:to_sym).reject { |s| s == :geom }) }

  def lowest_grade_numeric
    @lowest_grade_numeric ||=
      case lowest_grade
      when 'PR' then -2
      when 'PK' then -1
      when 'KG' then 0
      else
        lowest_grade.to_i
      end
  end

  def highest_grade_numeric
    @highest_grade_numeric ||=
      case highest_grade
      when 'PR' then -2
      when 'PK' then -1
      when 'KG' then 0
      else
        highest_grade.to_i
      end
  end

  def grade?(grade_level)
    grade_n = GRADE_KEYS.find_index(grade_level) - 2
    (lowest_grade_numeric..highest_grade_numeric).include?(grade_n)
  end

  def grades
    (lowest_grade_numeric..highest_grade_numeric).map do |n|
      [GRADE_KEYS[n + 2], GRADE_NAMES[n + 2]]
    end
  end

  def address
    [street1, street2, city, state, zip].compact.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def search
  end

  def apply
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  def lookup
    @geo_params = params_for_grade
    @feeder_patterns = FeederPattern.no_geom.includes(:school)
                       .containing(@geo_params[:lat], @geo_params[:lon])
                       .sort_by { |fp| School::GRADE_KEYS.index(fp.grade_levels.first) }

    unless @geo_params[:grade_level] == 'all'
      @feeder_patterns = @feeder_patterns.select { |pattern| pattern.school.grade?(@geo_params[:grade_level]) }
    end

    if @feeder_patterns.nil? || @feeder_patterns.length == 0
      return render json: nil, status: :not_found
    else
      @districts = @feeder_patterns.map { |fp| fp.school.district }.uniq
    end
  end

  def radius
    @geo_params = params_for_radius
    @schools = School.no_geom.within_radius(@geo_params[:lat].to_f,
                                            @geo_params[:lon].to_f,
                                            @geo_params[:radius])

    if @schools.nil? || @schools.length == 0
      return render json: nil, status: :not_found
    else
      @districts = @schools.map(&:district).uniq
    end
  end

  def district
    @geo_params = coord_params
    @district = District.containing(@geo_params[:lat].to_f,
                                    @geo_params[:lon].to_f).first


    if @district.nil? #|| @district.length == 0
      return render json: nil, status: :not_found
    else
      # HACK: Not sure why RGeo / ActiveRecord will not work with this
      #       field but this will shoehorn the geojson polygons out the door.
      @raw_geojson = JSON.parse(District.raw_geom(@district.id))
    end
  end

private

  def params_for_grade
    allowed_grades = School::GRADE_KEYS + ['all']
    unless allowed_grades.include?(params[:grade_level]&.downcase)
      gl = School::GRADE_KEYS.join(', ')
      return render json: { error: "Acceptable grade_level values are: #{gl}" },
             status: :unprocessable_entity
    end

    coord_params.merge({ grade_level: params[:grade_level].downcase })
  end

  def params_for_radius
    unless params[:radius].present? && params[:radius].to_f > 0.0
      return render json: { error: 'Radius should be a positive, numeric value,' },
             status: :unprocessable_entity
    end

    coord_params.merge({ radius: params[:radius].to_f })
  end

  def coord_params
    if params[:lat].blank? || params[:lon].blank?
      return render json: { error: 'Both Latitude and Longitude must be supplied.' },
             status: :unprocessable_entity
    end

    {
      lat: params[:lat].to_f,
      lon: params[:lon].to_f
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/_google_mapping_api.html.erb
    <% if ENV["GOOGLE_MAPS_JS_API_KEY"].blank? %>
    <script>console.log("To enable the Google auto-complete, you'll need to set a google maps API key in .env")</script>
    <% else %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_JS_API_KEY'] %>&libraries=places" data-turbolinks-track="reload"></script>
    <% end %>

app/views/app/_tabview.html.erb
<div class="tabs" role="tablist">
<% tabs.each do |tab_name| %>
  <div class="tab">
    <input type="radio" <%= (tab_name == default_tab) ? 'checked="checked"'.html_safe : '' %>
           class="display-toggle"
           name="tab_toggle"
           aria-hidden="true"
           aria-disabled="true"
           id="<%= tab_name %>" />
    <div class="tab-view">
<%= render "#{path_prefix}#{tab_name}" %>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>School Choice Delaware</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Quicksand:300,300italic,700,700italic">
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'app/google_mapping_api' %>
  </head>

  <body>
    <div class="sherpa container">
      <div class="banner row">
        <div class="col-12 text-center p-3">
          <%= link_to(root_path,  class: 'titling') do %>
            <%= image_tag('logo_title', height: 100, width: 300, alt: 'School Choice Delaware Search') %>
            <h1>School Choice SHERPA</h1>
          <% end %>
        </div>
      </div>
      <div class="body row justify-content-center p-lg-5 pb-1">
<%= yield %>
      </div>
      <div class="banner row">
        <div class="col-12 text-center p-3">
          <%= link_to(root_path) do %>
            <%= image_tag('logo', height: '70', width: '50', alt: 'School Choice Delaware Search') %>
          <% end %>
        </div>
      </div>
    </div>

    <footer class="text-center small">
      Site Design by Betsey Suchanic, Code by Eric L. Truitte, MBA.<br/>
      Code is available at <a href="http://github.com/omnilord/school-sherpa-de">GitHub</a>. Contributors welcome!</br>
      Cookies are not used for tracking purposes or to store information about end users.
    </footer>
  </body>
</html>

app/views/pages/apply.html.erb
<h2>Apply to a School</h2>

<div class="round-container row justify-content-center mt-3 p-4 pb-5">
  <div class="info-blurb">
    Comming Soon...
  </div>
</div>

app/views/pages/index.html.erb
<h2 class="text-center">Navigate School Choice in Delaware?</h2>

<div class="round-container row justify-content-center p-4 pb-5">
  <div class="col-12 col-lg-4 text-center nav_responsive">
    <%= link_to(learn_path, class: 'nav-item') do %>
      <%= image_tag('sherpa_icons-01.png', class: 'nav-icon', alt: '' ) %>
      <span class="nav-label">
        Learn About School Choice
      </span>
    <% end %>
  </div>
  <div class="col-12 col-lg-4 text-center nav_responsive">
    <%= link_to(search_path, class: 'nav-item') do %>
      <%= image_tag('sherpa_icons-02.png', class: 'nav-icon', alt: '') %>
      <span class="nav-label">
        Search for Schools
      </span>
    <% end %>
  </div>
  <div class="col-12 col-lg-4 text-center nav_responsive">
    <div class="nav-item">
      <%= link_to(apply_path) do %>
        <%= image_tag('sherpa_icons-03.png', class: 'nav-icon', alt: '') %>
      <span class="nav-label">
        Apply to a School
      </span>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <hr class="" />
  </div>
</div>

app/views/pages/learn.html.erb
<h2>Learn About School Choice</h2>

<div class="round-container row justify-content-center mt-3 p-4">
  <%= render 'app/tabview', path_prefix: 'pages/learn/',
                            tabs: %w[intro page0 page1 page2 page3 page4],
                            default_tab: 'intro' %>
</div>

<script charset="utf-8">
$(function () {
  var hash = location.hash.slice(1),
      navs = $('label.info-nav').on('click', function () {
        var nav_hash = $(this).attr('for');
        if (nav_hash != hash) {
          location.hash = hash = nav_hash;
        }
      });
  if (hash != '') {
    navs.filter('[for="' + hash + '"]').trigger('click');
  }
});
</script>

app/views/pages/learn/_intro.html.erb
<div class="learning-page">
  <div class="learning-intro learning-body row">
    <div class="col-12 text-center nav_responsive">
      <div class="learning-header mt-5 mb-5">
        <div class="learning-title info-nav p-2">School choice in Delaware is complex.</div>
      </div>
    </div>
    <div class="col-12">
      <p>
        Each Delaware household falls within a school district. The boundaries of each school district are also referred to as a feeder pattern. Unless, you, as a parent decides to send your child to a private school, charter school, or chooses to have your child attend a different public school, your child will attend their designated feeder pattern school. That is a big if, though, because of all the options you have as a parent. As a Delaware citizen your child is eligible to apply to attend any public school or charter school in the state. If this sounds confusing, you are in the right place. The purpose of the Delaware School Choice Sherpa project is to assist you and other Delaware parents navigate Delaware's school choice process. The content and tools on this website explain the steps of the school choice process and provide information to help you choose the school that is right for your child.
      </p>
    </div>
  </div>
  <label for="page0" aria-hidden="true" class="learning-next info-nav p-2 mt-3">About Choice</label>
</div>

app/views/pages/learn/_page0.html.erb
<div class="learning-page">
  <div class="learning-page-0 learning-body">
    <div class="info-blurb learning-left p-3">
      <p><strong><span class="title">What is School Choice?</strong></p>
      <p>
        The Delaware School Choice program offers a parent or guardian the opportunity
        to apply to schools of their choice in the case that the child's feeder school
        is not an appropriate fit for the child. Parents and guardians can choose to
        apply for their child to attend a traditional school outside of their feeder
        pattern, a charter school, a magnet school, a vo-tech school or a private school.
      </p>
    </div>
    <div class="info-blurb learning-right-top p-3">
      <p><strong><span class="title">What is a Feeder School?</strong></p>
      <p>
        Each household in Delaware is assigned a feeder pattern school. The assigned
        feeder pattern school is the public school children are designated to attend.
        If a parent decides not to go through the school choice process the feeder
        pattern school this is where a child will be educated.
      </p>
    </div>
    <div class="info-blurb learning-right-bottom p-3">
      <p><strong><span class="title">What is a Charter School?</strong></p>
      <p>
        Charter schools are independent, tuition-free public schools, serving students from kindergarten to 12th grade. The “charter” establishing each school is a contract, which states the school’s mission, program and measurable goals. Charter schools may be authorized by the State Department of Education or a local school district. They are accountable to their authorizer, parents and the public. Charter schools are different from traditional public schools in that they can only remain open as long as they deliver the results that they promise.
      </p>
      <p>
      Source: <a href="http://www.decharternetwork.org/About-Us/What-is-a-Charter-School">Delaware Charter Schools Network</a>
      </p>
    </div>
  </div>
  <label for="intro" aria-hidden="true" class="learning-prev info-nav p-2 mt-3">Intro</label>
  <label for="page1" aria-hidden="true" class="learning-next info-nav p-2 mt-3">Find a School</label>
</div>

app/views/pages/learn/_page1.html.erb
<div class="learning-page">
  <div class="learning-page-1 learning-body row">
    <div class="col-12 text-center nav_responsive">
      <div class="learning-header mt-5 mb-5">
        <div class="learning-step">1.</div>
        <div class="learning-title info-nav p-2">Find a School</div>
      </div>
    </div>

    <div class="col-12">
      <div class="text-center nav_responsive" style="float: right">
        <%= link_to(search_path, class: 'nav-item') do %>
          <%= image_tag('sherpa_icons-02.png', class: 'nav-icon') %>
          <div class="nav-label">
            Search for Schools
          </div>
        <% end %>
      </div>

      <p>Begin by researching schools. Review the school choice guide and look for schools that match your student’s priorities (related to academics and training, extracurriculars, preferences, diversity, and transportation).</p>

      <p>Visit schools that interest you and your student.</p>

      <p>Rank school choices. Consider each school’s capacity. What to consider?

        <dl>
          <dt>Academics and Training:</dt>
          <dd>What/how will your child learn and will the environment work for them? (Student Special Needs, Special Programs, Equipment, Technology)</dd>
          <dt>Preferences:</dt>
          <dd>Do you meet special considerations and will it affect your chance of admission? (Seat Capacity/Rejection Risk, School Proximity)</dd>
          <dt>Diversity:</dt>
          <dd>How might the staff/student population impact your child’s success? (Cultural/Social Comfort, Staff/Faculty)</dd>
          <dt>Transportation:</dt>
          <dd>How will your child get to/from school? (School Bus, Walking or Private Vehicle, Public Transportation)</dd>
          <dt>Extracurriculars:</dt>
          <dd>What kind of non-academic offerings does the school have? (Arts, Sports Club)</dd>
        </dl>
      </p>

      <p>Source: <a href="http://pacewilmington.nationbuilder.com/">The Pace Network Wilmington</a></p>
    </div>
  </div>
  <label for="page0" aria-hidden="true" class="learning-prev info-nav p-2 mt-3">About Choice</label>
  <label for="page2" aria-hidden="true" class="learning-next info-nav p-2 mt-3">Get Paperwork</label>
</div>

app/views/pages/learn/_page2.html.erb
<div class="learning-page">
  <div class="learning-page-2 learning-body row">
    <div class="col-12 text-center nav_responsive">
      <div class="learning-header mt-5 mb-5">
        <div class="learning-step">2.</div>
        <div class="learning-title info-nav p-2">Get Your Paperwork Ready</div>
      </div>
    </div>

    <div class="col-12">
      <p>
      In order for your child to be eligable for the school choice process they must first be enrolled at their feeder school (also known as school of residence). After you are sure they are enrolled the next step is to set up an account on <a href="https://www.schoolchoicede.org/Login.aspx?ReturnUrl=%2f" target="_blank">SchoolChoiceDE.com</a> and begin the application. Gather application information for the specific school district to which your child is applying by visting the <a href="https://www.doe.k12.de.us/site/Default.aspx?PageID=185" target="_blank">Delaware Department of Education's Choice Districts and Charters page</a>. Complete supplemental materials. Is additional information, such as an audition or interview, required?
      </p>
    </div>
  </div>
  <label for="page1" aria-hidden="true" class="learning-prev info-nav p-2 mt-3">Find a School</label>
  <label for="page3" aria-hidden="true" class="learning-next info-nav p-2 mt-3">Apply to a School</label>
</div>

app/views/pages/learn/_page3.html.erb
<div class="learning-page">
  <div class="learning-page-3 learning-body">
    <div class="learning-step-header text-center nav_responsive">
      <div class="learning-header mt-5 mb-5">
        <div class="learning-step">3.</div>
        <div class="learning-title info-nav p-2">Apply to a School</div>
      </div>
    </div>
    <div class="info-blurb learning-left p-3">
      <p><strong><span class="title">Timeline</strong></p>
      <p>
        <dl>
          <dt>Prior to November:</dt>
          <dd>Get Your Paperwork Ready</dd>
          <dt>First Monday in November:</dt>
          <dd>Window to submit school choice application opens</dd>
          <dt>Second Wednesday in January:</dt>
          <dd>Window to submit school choice application closes</dd>
          <dt>Late February:</dt>
          <dd>Parents are notified about invitation status</dd>
          <dt>Mid March:</dt>
          <dd>Deadline to accept or decline school choice invitation</dd>
        </dl>
      </p>
    </div>
    <div class="info-blurb learning-right p-3">
      <p><strong><span class="title">Additional Information</strong></p>
      <p>
        <ul>
          <li>Separate applications for each child must be submitted.</li>
          <li>Applications to multiple schools can be submitted.</li>
          <li>Invitation Status and Acceptance Criteria (Ordered by Priority)
            <ul>
              <li>Returning students who continue to meet the school requirements</li>
              <li>Siblings of students already enrolled and who will be returning to the school</li>
              <li>Children of employees</li>
              <li>Students living within the school district</li>
              <li>Students living outside the school district</li>
            </ul>
          </li>
        </ul>
      </p>
    </div>
  </div>
  <label for="page2" aria-hidden="true" class="learning-prev info-nav p-2 mt-3">Get Paperwork</label>
  <label for="page4" aria-hidden="true" class="learning-next info-nav p-2 mt-3">Apply to a School</label>
</div>

app/views/pages/learn/_page4.html.erb
<div class="learning-page">
  <div class="learning-page-4 learning-body row">
    <div class="col-12 text-center nav_responsive">
      <div class="learning-header mt-5 mb-5">
        <div class="learning-step">4.</div>
        <div class="learning-title info-nav p-2">Status Notification From Schools</div>
      </div>
    </div>

    <div class="col-12">
      <p>Check email/website for final decisions.</p>

      <p>Accept invitations for choice programs.</p>

      <p>Attend the orientation! Learn the rules, regulations, and fees/uniform requirements.</p>
    </div>
  </div>
  <label for="page3" aria-hidden="true" class="learning-prev info-nav p-2 mt-3">Apply to a School</label>
  <label for="nothing" aria-hidden="true" class="learning-next info-nav p-2 mt-3">GOOD LUCK!</label>
</div>

app/views/pages/search.html.erb
<h2 class="text-center">Search your Schools</h2>

<div class="round-container row justify-content-center p-4">
  <div class="col-12 col-lg-6 text-center">
    <div>
      <h3>Step 1 - Enter Your Address:</h3>
      <input name="google_place" id="google_place" type="text" class="place-autocomplete form-control" />
    </div>

    <div class="tabs mapping-operations" role="tablist">
      <h3>Step 2 - Choose An Operation:</h3>
      <label for="grade_level_view" role="tab">By Grade</label>
      <label for="radius_view" role="tab">By Radius</label>
      <label for="district_view" role="tab">District</label>
      <div class="tab">
        <input type="radio" class="display-toggle" name="tab_toggle" id="grade_level_view" />
        <div class="tab-view operation">
          <h3>Step 3:</h3>
          <select name="grade_level" id="grade_level" class="form-control" data-require-place="true">
            <option disabled="true" selected="true">Choose Grade</option>
            <option value="all">All Feeder Schools</option>
            <optgroup label="Grades">
              <option value="earlychildhood">Early Childhood</option>
              <option value="prekindergarten">Pre-Kindergarten</option>
              <option value="kindergarten">Kindergarten</option>
              <option value="one">First Grade</option>
              <option value="two">Second Grade</option>
              <option value="three">Third Grade</option>
              <option value="four">Fourth Grade</option>
              <option value="five">Fifth Grade</option>
              <option value="six">Sixth Grade</option>
              <option value="seven">Seventh Grade</option>
              <option value="eight">Eighth Grade</option>
              <option value="nine">Ninth Grade (Freshman)</option>
              <option value="ten">Tenth Grade (Sophomore)</option>
              <option value="eleven">Eleventh Grade (Junior)</option>
              <option value="twelve">Twelfth Grade (Senior)</option>
            </optgroup>
          </select>
          <button type="button" id="resolve_feeder_pattern"
                  style="width: 100%"
                  data-require-place="true"
                  disabled="disabled">
            Show My Feeder School
          </button>
        </div>
      </div>
      <div class="tab">
        <input type="radio" name="tab_toggle" id="radius_view" class="display-toggle" />
        <div class="tab-view operation">
          <h3>Step 3:</h3>
          <select name="radius" id="radius" class="form-control" data-require-place="true">
            <option disabled="true" selected="true">Choose Radius</option>
            <option disabled="true">&nbsp;</option>
            <option value="0.5">1/2 Mile</option>
            <option value="1">1 Mile</option>
            <option value="1.5">1 1/2 Miles</option>
            <option value="2">2 Miles</option>
            <option value="3">3 Miles</option>
            <option value="5">5 Miles</option>
          </select>
          <button type="button" id="resolve_radius"
                  style="width: 100%"
                  data-require-place="true"
                  disabled="disabled">
            Show Schools Near Me
          </button>
        </div>
      </div>
      <div class="tab">
        <input type="radio" name="tab_toggle" id="district_view" class="display-toggle" />
        <div class="tab-view operation">
          <h3>Step 3:</h3>
          <button type="button" id="resolve_district"
                  style="width: 100%"
                  data-require-place="true">
            Show School District Area
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12 col-lg-6 text-center">
    <div id="map" style="height: 350px; width: 100%"></div>
  </div>

  <div class="col-12 pt-2" id="results"></div>
  <script>
    $(function () { initMap(); });
  </script>
</div>